version: "3.7"
services:
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${PSQL_USER_DEV}
      - POSTGRES_PASSWORD=${PSQL_PASS_DEV}
      - POSTGRES_DB=${PSQL_DB_NAME_DEV}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env  

  go:
    container_name: go
    restart: always
    build:
      context: .
    depends_on:
      - db
        # condition: service_healthy # waiting until heathcheck of postgres is good
    ports:
      - "9090:9090"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      # - "53603:53603"
      - "8000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 7050:8080



volumes: 
  db-data: 
  pgadmin-data: 